name: JE SUIS YEMI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Job pour Windows
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build React app
        run: yarn build

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust to PATH
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri App for Windows
        run: yarn tauri build

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: src-tauri/target/release/bundle

  # Job pour Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Linux dependencies
        run: sudo apt-get install -y libgtk-3-dev build-essential

      - name: Install dependencies
        run: yarn install

      - name: Build React app
        run: yarn build

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust to PATH
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri App for Linux
        run: yarn tauri build

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: src-tauri/target/release/bundle

  # Job pour macOS
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build React app
        run: yarn build

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Rust to PATH
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri App for macOS
        run: yarn tauri build

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: src-tauri/target/release/bundle